#page title
page_title                                : Sereness                                  # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : DK                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://google.com
presskit_download_link                    : https://google.com                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Sereness
app_price                                 : $14.99
app_description                           : Meditate your way with Sereness, the customizeable meditation app that allows you to craft your own peaceful experience

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Solnaes Ventures ApS                                
your_link                                 : https://bing.com                     
your_city                                 : Aarhus, Denmark                                
email_address                             : google@gmail.com
facebook_username                         :                                           
instagram_username                        : google
twitter_username                          : google
github_username                           : google
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Customizable meditation sessions
    description                           : Create your own meditation sessions by selecting from a variety of sound clips, including nature sounds, guided meditations, and ambient music. Choose the perfect combination to help you relax and focus.
    fontawesome_icon_name                 : magic
    
  - title                                 : +1000 sound clips to choose from
    description                           : Our app offers a diverse range of sounds to choose from, including birds singing, ocean waves, and rain. You can also choose guided meditations and ambient music to help you relax and focus.
    fontawesome_icon_name                 : mobile

  - title                                 : Timer and session length options
    description                           : Set the length of your meditation session and use the timer feature to keep track of your time. You can also set reminders to help establish a consistent meditation practice.
    fontawesome_icon_name                 : fa-solid fa-clock

  - title                                 : Save your personal configurations in the cloud
    description                           : Once you have created your perfect meditation, you can save it in the cloud or locally for easy access in the future.
    fontawesome_icon_name                 : fa-solid fa-cloud

  - title                                 : Daily reminders and notifications
    description                           : Our app will send you daily reminders and notifications to help establish a consistent meditation practice.
    fontawesome_icon_name                 : adjust
  
  - title                                 : User-friendly interface and easy navigation
    description                           : The app has an intuitive and easy to use interface, making it easy to find the perfect meditation session for you.
    fontawesome_icon_name                 : star

  - title                                 : Set goals and track progress
    description                           : Keep track of your progress and set goals for your meditation practice.
    fontawesome_icon_name                 : fa-solid fa-chart-column

  - title                                 : Integration with other apps and wearables
    description                           : Our app can integrate with other apps and wearables, such as fitness trackers, to provide a more comprehensive view of your wellness.
    fontawesome_icon_name                 : link

  - title                                 : Share your custom meditations
    description                           : Share your custom meditations with friends and family, or discover new meditations created by other users.
    fontawesome_icon_name                 : fa-solid fa-share-nodes

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# Another feature:
# A variety of languages support: The app supports multiple languages, allowing you to meditate in the language that you feel most comfortable with.


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"







####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
